name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - run: apt-get update
    - run: apt-get install jq -y;
    - run: touch ./auth-service/src/main/resources/application.properties
    - run: echo "${{secrets.APPLICATION_YML}}" > ./auth-service/src/main/resources/application.properties
    - run: ./docker_push.sh
